name: Build & Upload artifact

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Node.js version to use for the build'
        type: string
        required: false
        default: '22.11.0'
      working-dir:
        description: 'Directory where the Astro project is located'
        type: string
        required: false
        default: './website'
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use for the build'
        type: string
        required: false
        default: '22.11.0'
      working-dir:
        description: 'Directory where the Astro project is located'
        type: string
        required: false
        default: './website'
    secrets:
      YOUTUBE_API_KEY:
        required: true
      SPOTIFY_REFRESH_TOKEN:
        required: true
      SPOTIFY_CLIENT_ID:
        required: true
      SPOTIFY_CLIENT_SECRET:
        required: true
      GOOGLE_ANALYTICS_ID:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    defaults:
      run:
        working-directory: ${{ inputs.working-dir }}
    services:
      libretranslate:
        image: libretranslate/libretranslate:latest
        ports: ['5000:5000']
        options: --env LT_LOAD_ONLY=en,pt,pt-br,de,fr,es,it
    timeout-minutes: 20
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
      artifact-url: ${{ steps.upload.outputs.artifact-url }}
      artifact-digest: ${{ steps.upload.outputs.artifact-digest }}

    steps:
    - uses: actions/checkout@v4 # Checkout the repository to the runner
    # - uses: actions/cache@v4
    #   with:
    #     path: ~/.npm
    #     key: ${{ runner.os }}-node-${{ hashFiles('${{ inputs.working-dir }}/package-lock.json') }}
    #     restore-keys: |
    #       ${{ runner.os }}-node-

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.working-dir }}/package-lock.json

    - name: Install dependencies with NPM
      run: npm ci
    
    - name: Wait for LibreTranslate # Wait for the LibreTranslate service to be ready
      run: |
        timeout 60 bash -c 'until curl --silent --output /dev/null --write-out "%{http_code}" http://localhost:5000/; do sleep 2; done'

    - name: Build with Astro
      run: npm run build
      env:
        LIBRETRANSLATE: http://localhost:5000/
        PUBLIC_BASE_URL: ${{ vars.PUBLIC_BASE_URL }}
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

    - name: Upload artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ vars.ARTIFACT_NAME }}
        path: ./dist
        retention-days: 90