name: Daily Deploy to Render.com

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:     # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Main

    steps:
      - name: Trigger Render Deploy
        id: render_deploy
        env:
          RENDER_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$RENDER_HOOK")
          echo "status=$response" >> $GITHUB_OUTPUT

      - name: Send Discord Notification
        if: always()
        env:
          DISCORD_HOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          status="${{ steps.render_deploy.outputs.status }}"
          
          if [ "$status" = "200" ]; then
            message="✅ Render deploy triggered successfully (Daily Deploy)."
          else
            message="❌ Failed to trigger Render deploy. HTTP Status: $status."
          fi

          payload="{\"content\": \"$message\"}"

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$payload" \
               "$DISCORD_HOOK"