name: Daily Deploy to Render.com

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:     # Allows manual triggering of the workflow

jobs:
  ci:
    uses: ./.github/workflows/ci.yml