name: Build & Deploy in Render CDN

on:
  push:
    branches: [ main, internationalization ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: deploy
    defaults:
      run:
        working-directory: ./website

    steps:
      - uses: actions/checkout@v3

      - name: Start LibreTranslate
        run: |
          docker pull libretranslate/libretranslate:latest
          docker run -d --name libretranslate \
            -p 5000:5000 \
            -e LT_LOAD_ONLY=en,pt,pt-br,de,fr,es,it \
            libretranslate/libretranslate:latest

      - name: Wait for LibreTranslate
        run: |
          until curl --silent http://localhost:5000/; do
            sleep 2
          done

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        env:
          LIBRETRANSLATE: http://localhost:5000/
          PUBLIC_BASE_URL: ${{ vars.PUBLIC_BASE_URL }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
        run: npm run build

      - name: Install Render CLI
        run: npm install -g @render/cli

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: render deploy \
          --service ${{ secrets.RENDER_SERVICE_ID }} \
          --dir ./dist

      - name: Stop LibreTranslate
        if: always()
        run: docker stop libretranslate
