name: Deploy Pages

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      artifact-name:
        description: "Artifact name used for deployment"
        value: ${{ jobs.deploy-pages.outputs.artifact-name }}
      download-path:
        description: "Path where the artifact was downloaded"
        value: ${{ jobs.deploy-pages.outputs.download-path }}
      pages-url:
        description: "Github Pages complete URL"
        value: ${{ jobs.deploy-pages.outputs.pages-url }}

env:
  PAGES_ARTIFACT_NAME: 'pages-artifact'

jobs:
  # Build & Upload artifact for Pages
  build-pages:
    uses: ./.github/workflows/build.yml
    with:
      build-command: 'npm run build:pages'
      artifact-name: 'pages-artifact'
    secrets: inherit

  deploy-pages:
    needs: build-pages
    runs-on: ubuntu-latest
    environment: deploy
    outputs:
      artifact-name: ${{ env.PAGES_ARTIFACT_NAME }}
      download-path: ${{ needs.build-pages.outputs.artifact-url }}
      pages-url: ${{ steps.deploy-pages.outputs.page_url}}

    steps:
    - name: Download artifact - ${{ env.PAGES_ARTIFACT_NAME }}
      uses: actions/download-artifact@v4
      with:
        # run-id: ${{ github.event.workflow_run.id }}
        artifact-ids: ${{ needs.build-pages.outputs.artifact-id }}
        path: ./${{ env.PAGES_ARTIFACT_NAME }}

    - name: Move files to dist directory
      run: mkdir -p dist && mv ${{ env.PAGES_ARTIFACT_NAME }}/* dist

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v5

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      id: deploy-pages
      with:
        artifact_name: ${{ env.PAGES_ARTIFACT_NAME }}

    - run: echo "Pages URL - ${{ steps.deploy-pages.outputs.page_url }}"