name: Deploy Pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build & Upload artifact"]
    types: [completed]

jobs:
  deploy-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: deploy
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ vars.ARTIFACT_NAME }}
      download-path: ${{ steps.download-artifact.outputs.download-path }}
      pages-url: ${{ steps.deploy-pages.outputs.page_url}}

    steps:
    - uses: actions/checkout@v4 # required to config pages

    - name: Download artifact - ${{ vars.ARTIFACT_NAME }}
      uses: actions/download-artifact@v4
      id: download-artifact
      with:
        name: ${{ vars.ARTIFACT_NAME }}
        path: ./${{ vars.ARTIFACT_NAME }}}}

    - run: echo "Artifact downloaded path - ${{ steps.download-artifact.outputs.download-path }}"

    - name: Move files to dist directory
      run: mv ${{ vars.ARTIFACT_NAME }}/* dist

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        name: ${{ vars.ARTIFACT_NAME }}
        path: ./dist

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      id: deploy-pages
      with:
        artifact_name: ${{ vars.ARTIFACT_NAME }}

    - run: echo "Pages URL - ${{ steps.deploy-pages.outputs.page_url }}"

  notify:
    needs: deploy-pages
    runs-on: ubuntu-latest
    environment: discord
    if: ${{ needs.deploy-pages.result == 'success' }}

    steps:
      - name: Send Discord notification
        uses: stegzilla/discord-notify@v4
        with:
          webhook_url: ${{ secrets.DEPLOY_PAGES }}
          username: "GHA deploy-pages"
          title: "Deploy Pages Success"
          message: |
            ✅ Deploy to Github Pages succeeded for **${{ github.repository }}**
            - GHA run: #${{ github.run_number }}
            - Artifact Name: `${{ needs.deploy-pages.outputs.artifact-name }}`
            - Download Path: `${{ needs.deploy-pages.outputs.download-path }}`
            - **Pages URL: `${{ needs.deploy-pages.outputs.pages-url }}`**