name: Trigger Render Deploy

on:
  workflow_dispatch:
  workflow_call:

jobs:
  trigger-render-deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - run: |
        curl -X POST \
          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
          -H "accept: application/json" \
          -H "authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "content-type: application/json" \
          -d '{"clearCache":"clear","commitId":"'"${{ github.sha }}"'"}'